project:
  name: Mobile Money Fraud Simulator
  version: 0.1.0
  author: Ranganath Acharya

simulation:
  random_seed: 2026
  days: 365

population:

  customers: 100000

capacity:

  customers_per_agent: 800

  agents_per_master: 20

  masters_per_super: 20

  merchants_per_agent: 25

output:
  csv: true
  parquet: true
  overwrite: true

fraud:
  enabled: true
  ghost_customer: 0.005
  referral_abuse: 0.003
  dealer_collusion: 0.001
  dealer_ato: 0.0005

telecom:
  esim_swap_rate: 0.0002
  sim_swap_rate: 0.001
  pin_reset_rate: 0.005