from enum import Enum


class EventType(str, Enum):

    # Customer

    CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED"

    KYC_COMPLETED = "KYC_COMPLETED"

    # Wallet

    WALLET_CREATED = "WALLET_CREATED"

    # Telecom

    SIM_ACTIVATED = "SIM_ACTIVATED"

    SIM_SWAP = "SIM_SWAP"

    ESIM_PROVISIONED = "ESIM_PROVISIONED"

    PIN_RESET = "PIN_RESET"

    DEVICE_CHANGED = "DEVICE_CHANGED"

    LOGIN = "LOGIN"

    # Financial

    CASH_IN = "CASH_IN"

    CASH_OUT = "CASH_OUT"

    P2P_TRANSFER = "P2P_TRANSFER"

    MERCHANT_PAYMENT = "MERCHANT_PAYMENT"

    BILL_PAYMENT = "BILL_PAYMENT"

    FLOAT_TRANSFER = "FLOAT_TRANSFER"

    COMMISSION_PAID = "COMMISSION_PAID"

    # Fraud

    ACCOUNT_TAKEOVER = "ACCOUNT_TAKEOVER"

    GHOST_CUSTOMER = "GHOST_CUSTOMER"

    DEALER_COLLUSION = "DEALER_COLLUSION"

    REFERRAL_ABUSE = "REFERRAL_ABUSE"

    COMMISSION_FARMING = "COMMISSION_FARMING"